### ISSUE TITLE
Custom Nodes

### ISSUE THREAD

**Issue by Dyceman** [iliyaZelenko/tiptap-vuetify#135]
Does this support custom created nodes in a compiled environment, such as NuxtJS?

**Comment by ShisunXia** [comment]
I have the same question.

**Comment by iliyaZelenko** [comment]
You mean [this](https://github.com/iliyaZelenko/tiptap-vuetify#native-extensions)? In theory, everything should work in nuxt. Let me know if you meant something else.

I have the demo for Nuxt [here](https://github.com/iliyaZelenko/tiptap-vuetify-nuxt). But now there’s a [bug](https://github.com/iliyaZelenko/tiptap-vuetify-nuxt/issues/4) in order to work with the Nuxt, you need a version of `tiptap-vuetify` no higher than `2.11.1`.

**Comment by ShisunXia** [comment]
> You mean [this](https://github.com/iliyaZelenko/tiptap-vuetify#native-extensions)? In theory, everything should work in nuxt. Let me know if you meant something else.

The example you showed is custom extension not custom node. [This](https://github.com/scrumpy/tiptap#create-a-node-as-a-vue-component) is the a custom node example from Tiptap. Is there a way to create such thing?

**Comment by iliyaZelenko** [comment]
You can use there not only extensions, but also nodes. This also [works in the tiptap](https://github.com/scrumpy/tiptap#editor-properties) itself.
![image](https://user-images.githubusercontent.com/13103045/75325073-d886ea00-5880-11ea-9bd6-7e176f0d6d57.png)
