### ISSUE TITLE
Image support?

### ISSUE THREAD

**Issue by assoft** [iliyaZelenko/tiptap-vuetify#16]
Are you considering supporting the image/embeds extension? When can you think about it?

**Comment by iliyaZelenko** [comment]
Hey, @assoft. 

First of all, thanks for giving me a star, this is what motivates me to work with the project. 

If you need it, then I will start working on it today, I think it will take a few days at most, I hope it will not be long for you?

I want this project to become popular, so I need to satisfy the desires of users.

**Comment by iliyaZelenko** [comment]
Do you have any ideas about uploading images?

**Comment by assoft** [comment]
Hi @iliyaZelenko,

First of all, I want to thank you for starting this project.

**I think you've completed a serious shortcoming to Vuetify.**

API is perhaps the best way to upload images

No, absolutely no rush for me

I wish you good work.

_i'm sorry i'm not good enough to speak english._

**Comment by assoft** [comment]
<img width="485" alt="Example On Nuxt.js" src="https://user-images.githubusercontent.com/835239/59117282-096f6980-8956-11e9-9b53-f99e77783273.png">

Thank you @iliyaZelenko

**Comment by Flambe** [comment]
I'd definitely be interested in this too!

What ideas were you looking for @iliyaZelenko ?

**Comment by iliyaZelenko** [comment]
Thanks for the support guys. I work on it and I have a lot of plans. I will try to release the update as soon as I can.

This has been a little delayed since I am working in the company now and I am changing the project structure cardinally so that it is easier for further development and flexible for user expansion. You will have the functionality to easily add your own buttons (not necessarily buttons) and change existing ones.

I plan to add the extension for loading images into a separate package in order to make the editor modular. I will create the same separate package for the extension with which you can add emoticons.

Maybe I will also have to create a separate package for each package so that these extensions can be used in tiptap without the need for vuetify.

For the images extension, I plan to make a system of plugins, with the help of which you can choose hosting for downloading or your own REST API.

> What ideas were you looking for @iliyaZelenko ?

These can be any of your ideas. For example, how do I make this as flexible as possible for users.

I also added the ability to choose where to display the buttons: in the toolbar or in the tooltip.

**Comment by Flambe** [comment]
No rush from me either.

The separate packages sounds like a really good idea, then we can just pull in what we need.

I'm not sure what the best practice for this is, but maybe let the user pass an async callback which lets them do the API query themselves? 

Really liking your plans for the future!

**Comment by sangemi** [comment]
Hi, I also wait image support!
Please consider about AWS S3 upload :-) and Drag and drop

**Comment by websitevirtuoso** [comment]
IT would be good, hope we will get it soon

**Comment by iliyaZelenko** [comment]
Added in `2.6.0`.

![image](https://user-images.githubusercontent.com/13103045/68091902-39cc1d00-fe8e-11e9-89bd-f4f50a116f65.png)

Use `Image` extension for this. Example [here](https://codesandbox.io/s/vue-template-6p9wp?fontsize=14&module=%2Fsrc%2Fexamples%2FSimple.vue).

Note: since the original extension works through base64, then I had to do it too. That is, the pictures are not uploaded to the server, but stored in the editor’s content. In the future I plan to make a real upload, I will have to create my own image extension for tiptap. Also I will try to fix [resize issue](https://github.com/scrumpy/tiptap/issues/333) in my extension.

**Comment by nibytes** [comment]
> I will try to fix resize issue in my extension.
Hello Ilia, did you manage to fix it?

**Comment by iliyaZelenko** [comment]
@nibytes not yet. I will let you know when will be ready.

**Comment by rajesh-h** [comment]
@iliyaZelenko Do you think you will be completing this image upload soon? It's a much awaited feature.

**Comment by catthecreator** [comment]
Hi! I also do not have enough load images. 
You did a great job! Thank you very much!

**Comment by ksdhir** [comment]
Does Image Uploader support file types like `.jpeg` or `.png` ?
Also it would be great to add Image size limit feature i.e 5 mb max file size. Does the extension currently support this?

**Comment by iliyaZelenko** [comment]
@ksdhir the default uploadof pictures works through bass64 (`.jpeg` and `.png` must be supported), this can be seen by `src` of image. This editor gives you the flexibility to upload pictures to your backend server. You must write the download code yourself. In the end, you will need to transfer the link to the downloaded image for this editor to use it. More info [here](https://github.com/iliyaZelenko/tiptap-vuetify#custom-image-upload-components).

**Comment by nuolmakara16** [comment]
@avgeeklucky Sorry! I am using custom image upload components in my nuxt project, everything seem to work fine until I try to use it with store using this.$store. I wonder are there anyway I could access store in the custom component? I'm really appreciate your answer!

**Comment by abdulrahmank** [comment]
This is a great feature indeed! 

Just curious was there any fix for resizing?
@iliyaZelenko  thank you for such a great project
