### ISSUE TITLE
Problems registering Vuetify components in Nuxt

### ISSUE THREAD

**Issue by HELSIS666** [iliyaZelenko/tiptap-vuetify#18]
Hi, I had problems registering Vuetify components in a bunch of Nuxt ( TypeScript ) + Vuetify ( VuetifyLoaderPlugin ). I was able to solve this, but I'm not sure that this is the easy way. For the most part, this post may be a hint, not a problem, please add this or your method to the documentation. My solution is to re-enforce the registration of some Vuetify components.

> Although they are automatically registered, I'm confused :)

Error Example:
```
[Vue warn]:  Unknown custom element: <v-card> - did you register 
the component correctly? For recursive components, 
make sure to provide the "name" option.
```

Solution:
```ts
//~/plugins/vuetify*

import Vue from 'vue';
import Vuetify, { VTooltip, VToolbar, VCard, VIcon, VBtn } from 'vuetify/lib';
import { TiptapVuetifyPlugin } from 'tiptap-vuetify';

import colors from 'vuetify/es5/util/colors';
import '@mdi/font/css/materialdesignicons.css';
import 'tiptap-vuetify/dist/main.css';

const iconfont = 'mdi';

Vue.use(Vuetify, {
  iconfont: iconfont,
  options: {
    customProperties: true,
  },
  theme: {
    primary: colors.deepPurple.base,
    secondary: colors.purple.darken3,
    accent: colors.pink.darken2,
    error: colors.red.darken4,
    warning: colors.orange.darken4,
    info: colors.blue.base,
    success: colors.green.base,
  },
  components: {
    VTooltip,
    VToolbar,
    VCard,
    VIcon,
    VBtn,
  },
});

Vue.use(TiptapVuetifyPlugin, {
  iconsGroup: iconfont,
});
```

**Comment by iliyaZelenko** [comment]
Thank you very much for finding the problem and showing how to fix it, it is very useful.

It seems `VuetifyLoaderPlugin` is not working for this library (most likely for all libraries
 in `node_modules`). How you solved the problem is the most obvious way for me.

I [added this problem](https://github.com/iliyaZelenko/tiptap-vuetify#a-la-carte--vuetifyloaderplugin) in the `README.md` so that people find how to solve this problem.

I think I have an idea how to solve this issue at the level of the package itself. Most likely in the future version this error will not occur.

I am also glad that you have no other problems when using this package with Nuxt.js.

Thank you again.
