### ISSUE TITLE
tiptapVuetifyPlugin is undefined

### ISSUE THREAD

**Issue by konstantinvoronoy** [iliyaZelenko/tiptap-vuetify#32]
Hi!

When I installed tiptap-vuetify and tried to use it, I got this error in console:

Error in mounted hook: "TypeError: vue__WEBPACK_IMPORTED_MODULE_0___default.a.prototype.tiptapVuetifyPlugin is undefined"

I've checked the code thousands of times and it seems exactly like in docs. I have no idea what to do with that. Could anyone help?

**Comment by iliyaZelenko** [comment]
Hi, @konstantinvoronoy.

I see that you have checked the code many times, but the problem seems to be that `Vue.use` was not called.

```
import Vue from 'vue'

// first it
Vue.use(Vuetify)
// AFTER Vue.use(Vuetify) !!!
Vue.use(TiptapVuetifyPlugin) // <-- THIS
```

I don’t even know what else could be the cause of the error.

That's where `prototype.tiptapVuetifyPlugin` is sets:
https://github.com/iliyaZelenko/tiptap-vuetify/blob/627faf34eff575048d41782a35f2b75ddafad4ab/src/main.ts#L38

It seems that other users of this package did not have such a problem.

I would be happy to help more, but the error is not obvious.

**Comment by konstantinvoronoy** [comment]
Thanks, man! I found it! I started learning vuejs about a month ago. And when I made a project I used: `import Vue from 'vue/dist/vue.js';`

And since then I didn't change it. And now I've changed it to `import Vue from 'vue';` and it works! Thank you a lot!
